import { useState, useEffect, useCallback, useMemo } from 'react';
import type { Incident, AIInsight } from '../types';
import { MOCK_INCIDENTS, MOCK_AI_INSIGHTS, STADIUM_VENUES } from '../mockData';
import { TypeIcon, SeverityBadge } from '../components/OpsCenter/Shared';
import { CrowdGauge } from '../components/OpsCenter/CrowdGauge';
import { AIReportCard } from '../components/OpsCenter/AIReportCard';
import { IncidentCard } from '../components/OpsCenter/IncidentCard';
import './OpsCenter.css';

interface Props { onBack: () => void; }

type OpsTab = 'overview' | 'incidents' | 'crowd' | 'ai-reports';
type UserView = 'ops' | 'security' | 'exec';

const venue = STADIUM_VENUES[0];

export default function OpsCenter({ onBack }: Props) {
  const [activeTab, setActiveTab] = useState<OpsTab>('overview');
  const [userView, setUserView] = useState<UserView>('ops');
  const [incidents, setIncidents] = useState<Incident[]>(() => {
    try {
      const stored = localStorage.getItem('nexus_ops_incidents');
      if (stored) {
        const parsed = JSON.parse(stored);
        return parsed.map((inc: any) => ({
          ...inc,
          reportedAt: new Date(inc.reportedAt)
        }));
      }
    } catch {
      // ignore
    }
    return MOCK_INCIDENTS;
  });
  const [selectedIncident, setSelectedIncident] = useState<Incident | null>(() => {
    try {
      const stored = localStorage.getItem('nexus_ops_incidents');
      if (stored) {
        const parsed = JSON.parse(stored);
        if (parsed.length > 0) {
          return {
            ...parsed[0],
            reportedAt: new Date(parsed[0].reportedAt)
          };
        }
      }
    } catch {}
    return MOCK_INCIDENTS[0];
  });
  const [insights] = useState<AIInsight[]>(MOCK_AI_INSIGHTS);
  const [_tick, setTick] = useState(0);
  const [generatingReport, setGeneratingReport] = useState(false);
  const [situationReport, setSituationReport] = useState('');

  // Persist incidents to localStorage
  useEffect(() => {
    localStorage.setItem('nexus_ops_incidents', JSON.stringify(incidents));
  }, [incidents]);

  // Live clock tick for reactive updates
  useEffect(() => {
    const interval = setInterval(() => setTick(t => t + 1), 10000);
    return () => clearInterval(interval);
  }, []);

  const { activeIncidents, resolvedCount, activeCount, criticalCount } = useMemo(() => {
    const active = incidents.filter(i => i.status !== 'resolved');
    return {
      activeIncidents: active,
      resolvedCount: incidents.length - active.length,
      activeCount: active.length,
      criticalCount: active.filter(i => i.severity === 'high' || i.severity === 'critical').length,
    };
  }, [incidents]);

  const generateSituationReport = useCallback(() => {
    setGeneratingReport(true);
    setSituationReport('');
    const report = `═══ AI SITUATION REPORT — ${new Date().toLocaleTimeString()} ═══
Generated by: NexusAI Incident Response Agent (Gemini 1.5 Pro)
Stadium: AT&T Stadium, Dallas | Match: BRA 2–1 ARG | 67'

OPERATIONAL STATUS: ⚠️  YELLOW

┌─ INCIDENTS ────────────────────────────────
│ ACTIVE:    ${activeCount} incidents (${criticalCount} HIGH/CRITICAL)
│ RESOLVED:  ${resolvedCount} in last 2 hours
└────────────────────────────────────────────

┌─ CROWD ANALYTICS ──────────────────────────
│ Peak density: Section 112 (99%) — CRITICAL
│ Gate A trending ↑ to dangerous levels
│ AI predicts mass exodus in ~23 minutes
└────────────────────────────────────────────

┌─ MEDICAL ──────────────────────────────────
│ 1 active case: Heat exhaustion Sec 112
│ EMS Alpha on scene — patient stable
│ 3 additional at-risk individuals flagged (heat)
└────────────────────────────────────────────

┌─ SECURITY ─────────────────────────────────
│ No active threats. All clear.
│ VIP zone near capacity — monitoring.
└────────────────────────────────────────────

┌─ AI RECOMMENDATIONS ───────────────────────
│ 1. URGENT: Pre-stage 8 exit marshals NOW
│ 2. HIGH: Activate cooling stations SB-3,4
│ 3. HIGH: Alert Metro Line 3 for surge
│ 4. MED: Mobile ordering for Secs 108-120
└────────────────────────────────────────────

Next auto-report in: 2 minutes
Confidence: 95% | Model: gemini-1.5-pro | Tokens: 1,847`;

    let i = 0;
    const interval = setInterval(() => {
      if (i <= report.length) {
        setSituationReport(report.slice(0, i));
        i += 8;
      } else {
        clearInterval(interval);
        setGeneratingReport(false);
      }
    }, 20);
    return () => clearInterval(interval);
  }, [activeCount, resolvedCount, criticalCount]);

  const resolveIncident = (id: string) => {
    setIncidents(prev => prev.map(inc =>
      inc.id === id ? { ...inc, status: 'resolved' as const, updatedAt: new Date() } : inc
    ));
    if (selectedIncident?.id === id) {
      setSelectedIncident(null);
    }
  };

  return (
    <div className="ops-center" role="main" aria-label="NexusAI Operations Command Center">
      {/* Ops Header */}
      <header className="ops-header" role="banner">
        <div className="ops-header-inner">
          <div className="ops-logo-group">
            <button className="btn btn-ghost btn-sm back-btn-ops" onClick={onBack} id="ops-back-btn" aria-label="Back to portal">← Back</button>
            <div className="ops-logo">
              <div className="ops-logo-icon">⚡</div>
              <div>
                <div className="ops-logo-name">OPS COMMAND CENTER</div>
                <div className="ops-logo-sub">NexusAI Stadium · AT&T Stadium, Dallas</div>
              </div>
            </div>
          </div>

          <div className="ops-header-center">
            <div className="ops-stat-pill" aria-label={`${activeCount} active incidents`}>
              <span className="stat-pill-num">{activeCount}</span>
              <span>Active Incidents</span>
            </div>
            <div className={`ops-stat-pill ${criticalCount > 0 ? 'stat-pill-red' : ''}`} aria-label={`${criticalCount} critical alerts`}>
              <span className="stat-pill-num">{criticalCount}</span>
              <span>Critical Alerts</span>
            </div>
            <div className="ops-stat-pill" aria-label="74,320 attendance">
              <span className="stat-pill-num">74.3K</span>
              <span>Attendance</span>
            </div>
          </div>

          <div className="ops-header-right">
            {/* RBAC View Switcher */}
            <div className="view-switcher" role="group" aria-label="Switch user role view">
              {(['ops', 'security', 'exec'] as UserView[]).map(v => (
                <button
                  key={v}
                  className={`view-btn ${userView === v ? 'view-btn-active' : ''}`}
                  onClick={() => setUserView(v)}
                  aria-pressed={userView === v}
                  id={`view-${v}-btn`}
                >
                  {v === 'ops' ? '⚡' : v === 'security' ? '🔒' : '👑'}
                  {v.toUpperCase()}
                </button>
              ))}
            </div>

            <div className="ops-live-badge" role="status">
              <span className="status-dot live" aria-hidden="true"></span>
              <span>SYSTEM LIVE</span>
            </div>
          </div>
        </div>

        {/* Ops Tab Bar */}
        <div className="ops-tabs" role="tablist">
          {([
            { id: 'overview', icon: '📊', label: 'Overview' },
            { id: 'incidents', icon: '🚨', label: `Incidents (${activeCount})` },
            { id: 'crowd', icon: '👥', label: 'Crowd Analytics' },
            { id: 'ai-reports', icon: '🤖', label: 'AI Reports' },
          ] as const).map(tab => (
            <button
              key={tab.id}
              className={`ops-tab ${activeTab === tab.id ? 'ops-tab-active' : ''}`}
              onClick={() => setActiveTab(tab.id)}
              role="tab"
              aria-selected={activeTab === tab.id}
              id={`ops-tab-${tab.id}`}
            >
              <span aria-hidden="true">{tab.icon}</span>
              {tab.label}
            </button>
          ))}
        </div>
      </header>

      {/* Content */}
      <div className="ops-content">

        {/* ====== OVERVIEW TAB ====== */}
        {activeTab === 'overview' && (
          <div className="overview-tab page-enter">
            {/* KPI Row */}
            <div className="kpi-row" role="list" aria-label="Key performance indicators">
              {[
                { label: 'Stadium Capacity', value: '92.9%', sub: '74,320 / 80,000', color: 'var(--nexus-gold)', icon: '🏟️' },
                { label: 'Active AI Agents', value: '48', sub: 'All systems nominal', color: 'var(--nexus-green)', icon: '🤖' },
                { label: 'Avg Response Time', value: '2.1m', sub: 'Incident response', color: 'var(--nexus-cyan)', icon: '⚡' },
                { label: 'Fan Satisfaction', value: '4.7★', sub: 'Real-time NPS', color: 'var(--nexus-gold)', icon: '😊' },
                { label: 'AI Accuracy', value: '94.2%', sub: 'Prediction precision', color: 'var(--nexus-green)', icon: '🎯' },
                { label: 'System Uptime', value: '99.97%', sub: 'Last 30 days', color: 'var(--nexus-cyan)', icon: '✅' },
              ].map(kpi => (
                <div key={kpi.label} className="kpi-card glass-card" role="listitem" aria-label={`${kpi.label}: ${kpi.value}`}>
                  <div className="kpi-icon" style={{ color: kpi.color }}>{kpi.icon}</div>
                  <div className="kpi-value" style={{ color: kpi.color }}>{kpi.value}</div>
                  <div className="kpi-label">{kpi.label}</div>
                  <div className="kpi-sub">{kpi.sub}</div>
                </div>
              ))}
            </div>

            <div className="overview-main-grid">
              {/* Active Incidents Summary */}
              <div className="overview-incidents glass-card">
                <div className="card-header-row">
                  <h3>🚨 Active Incidents</h3>
                  <button className="btn btn-ghost btn-sm" onClick={() => setActiveTab('incidents')}>View All →</button>
                </div>
                <div className="inc-summary-list">
                  {activeIncidents.map(inc => (
                    <div key={inc.id} className={`inc-summary-item severity-${inc.severity}`}>
                      <TypeIcon type={inc.type} />
                      <div className="inc-sum-content">
                        <div className="inc-sum-title">{inc.title}</div>
                        <div className="inc-sum-loc">{inc.location.description}</div>
                      </div>
                      <SeverityBadge severity={inc.severity} />
                    </div>
                  ))}
                  {activeCount === 0 && (
                    <div className="no-incidents">
                      <span>✅</span>
                      <span>All clear — no active incidents</span>
                    </div>
                  )}
                </div>
              </div>

              {/* AI Situation Report */}
              <div className="overview-sitrep glass-card">
                <div className="card-header-row">
                  <h3>🤖 AI Situation Report</h3>
                  <button
                    className={`btn btn-primary btn-sm ${generatingReport ? 'btn-generating' : ''}`}
                    onClick={generateSituationReport}
                    disabled={generatingReport}
                    id="generate-sitrep-btn"
                    aria-label="Generate AI situation report"
                  >
                    {generatingReport ? '⏳ Generating...' : '✨ Generate Now'}
                  </button>
                </div>
                {situationReport ? (
                  <pre className="sitrep-output">{situationReport}</pre>
                ) : (
                  <div className="sitrep-placeholder">
                    <span>🔮</span>
                    <p>Click "Generate Now" to create an AI situation report using Gemini 1.5 Pro.</p>
                    <p className="sitrep-sub">Auto-generates every 2 minutes during live operations.</p>
                  </div>
                )}
              </div>

              {/* Top AI Insight */}
              <div className="overview-insight glass-card">
                <div className="card-header-row">
                  <h3>🔮 Top AI Prediction</h3>
                  <span className="badge badge-red">89% Confidence</span>
                </div>
                <div className="top-insight">
                  <div className="insight-alert-title">{insights[0].title}</div>
                  <p className="insight-alert-body">{insights[0].content}</p>
                  {insights[0].actionItems?.slice(0, 3).map((item, i) => (
                    <div key={i} className="action-item">
                      <span className="action-num">{i + 1}</span>
                      <span>{item}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ====== INCIDENTS TAB ====== */}
        {activeTab === 'incidents' && (
          <div className="incidents-tab page-enter">
            <div className="incidents-layout">
              {/* Left: Incident List */}
              <div className="incident-list-col">
                <div className="col-header">
                  <h3>All Incidents</h3>
                  <div className="col-header-right">
                    <span className="badge badge-red">{activeCount} Active</span>
                  </div>
                </div>
                <div className="incident-list" role="list">
                  {incidents.map(inc => (
                    <IncidentCard
                      key={inc.id}
                      incident={inc}
                      isSelected={selectedIncident?.id === inc.id}
                      onClick={() => setSelectedIncident(inc)}
                    />
                  ))}
                </div>
              </div>

              {/* Right: Incident Detail */}
              <div className="incident-detail-col">
                {selectedIncident ? (
                  <div className="incident-detail glass-card">
                    <div className="detail-header">
                      <div className="detail-title-row">
                        <TypeIcon type={selectedIncident.type} />
                        <h3>{selectedIncident.title}</h3>
                        <SeverityBadge severity={selectedIncident.severity} />
                      </div>
                      <div className="detail-meta">
                        <span>📍 {selectedIncident.location.description}</span>
                        <span>·</span>
                        <span>Reported by: {selectedIncident.reportedBy}</span>
                        <span>·</span>
                        <span>{selectedIncident.reportedAt.toLocaleTimeString()}</span>
                      </div>
                    </div>

                    <p className="detail-description">{selectedIncident.description}</p>

                    {/* AI Action Plan */}
                    {selectedIncident.aiPlan && (
                      <div className="ai-plan-box">
                        <div className="ai-plan-header">
                          <span>✨</span>
                          <strong>AI-Generated Action Plan</strong>
                          <span className="badge badge-blue">Gemini 1.5 Pro</span>
                        </div>
                        <pre className="ai-plan-content">{selectedIncident.aiPlan}</pre>
                      </div>
                    )}

                    {/* Timeline */}
                    <div className="incident-timeline">
                      <div className="timeline-label">📋 Activity Timeline</div>
                      {selectedIncident.updates.map(upd => (
                        <div key={upd.id} className={`timeline-item ${upd.isAiGenerated ? 'timeline-ai' : 'timeline-human'}`}>
                          <div className="timeline-dot" />
                          <div className="timeline-content">
                            <div className="timeline-author">
                              {upd.isAiGenerated ? '✨ AI Orchestrator' : upd.author}
                            </div>
                            <div className="timeline-text">{upd.content}</div>
                            <div className="timeline-time">{upd.timestamp.toLocaleTimeString()}</div>
                          </div>
                        </div>
                      ))}
                    </div>

                    {/* Actions */}
                    {selectedIncident.status !== 'resolved' && (
                      <div className="detail-actions">
                        <button
                          className="btn btn-primary"
                          onClick={() => resolveIncident(selectedIncident.id)}
                          id={`resolve-${selectedIncident.id}-btn`}
                          aria-label={`Mark incident ${selectedIncident.title} as resolved`}
                        >
                          ✅ Mark Resolved
                        </button>
                        <button className="btn btn-ghost" id="escalate-btn" aria-label="Escalate this incident">
                          ↑ Escalate
                        </button>
                        <button className="btn btn-ghost" id="add-update-btn" aria-label="Add update to incident">
                          + Add Update
                        </button>
                      </div>
                    )}
                  </div>
                ) : (
                  <div className="no-incident-selected">
                    <span>🚨</span>
                    <p>Select an incident to view details and AI action plan</p>
                  </div>
                )}
              </div>
            </div>
          </div>
        )}

        {/* ====== CROWD ANALYTICS TAB ====== */}
        {activeTab === 'crowd' && (
          <div className="crowd-tab page-enter">
            <div className="crowd-header-row">
              <h3>Live Crowd Analytics — AT&T Stadium</h3>
              <div className="crowd-legend" aria-label="Crowd density legend">
                <span style={{ color: 'var(--nexus-green)' }}>● Clear</span>
                <span style={{ color: 'var(--nexus-gold)' }}>● Moderate</span>
                <span style={{ color: 'var(--nexus-red)' }}>● Critical</span>
              </div>
            </div>

            {/* Gauges */}
            <div className="gauges-grid">
              {venue.zones.map(zone => (
                <CrowdGauge key={zone.id} density={zone.density} name={zone.name} status={zone.status} />
              ))}
            </div>

            {/* Zone Table */}
            <div className="crowd-table-wrap glass-card">
              <div className="table-header">
                <h3>Zone Detail View</h3>
                <span className="badge badge-blue">AI Predictions Active</span>
              </div>
              <div role="table" aria-label="Stadium crowd zones table">
                <div role="rowgroup">
                  <div className="table-head" role="row">
                    <div role="columnheader">Zone</div>
                    <div role="columnheader">Occupancy</div>
                    <div role="columnheader">Density</div>
                    <div role="columnheader">Flow/min</div>
                    <div role="columnheader">AI Pred (15m)</div>
                    <div role="columnheader">Status</div>
                  </div>
                </div>
                <div role="rowgroup">
                  {venue.zones.map(zone => (
                    <div key={zone.id} className={`table-row zone-row-${zone.status}`} role="row">
                      <div role="cell" className="zone-cell-name">{zone.name}</div>
                      <div role="cell">{zone.currentOccupancy.toLocaleString()} / {zone.capacity.toLocaleString()}</div>
                      <div role="cell">
                        <div className="density-bar-inline">
                          <div className="density-fill" style={{
                            width: `${zone.density}%`,
                            background: zone.density > 85 ? 'var(--nexus-red)' : zone.density > 65 ? 'var(--nexus-gold)' : 'var(--nexus-green)'
                          }} />
                          <span>{zone.density}%</span>
                        </div>
                      </div>
                      <div role="cell">{zone.flowRate}</div>
                      <div role="cell" className="pred-cell">
                        {zone.prediction15min !== undefined ? (
                          <span style={{ color: zone.prediction15min < zone.density ? 'var(--nexus-green)' : 'var(--nexus-gold)' }}>
                            {zone.prediction15min > zone.density ? '↑' : '↓'} {zone.prediction15min}%
                          </span>
                        ) : '—'}
                      </div>
                      <div role="cell">
                        <span className={`badge ${zone.status === 'critical' ? 'badge-red' : zone.status === 'crowded' ? 'badge-gold' : zone.status === 'moderate' ? 'badge-blue' : 'badge-green'}`}>
                          {zone.status.toUpperCase()}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ====== AI REPORTS TAB ====== */}
        {activeTab === 'ai-reports' && (
          <div className="ai-reports-tab page-enter">
            <div className="reports-header">
              <div>
                <h3>AI Intelligence Reports</h3>
                <p>Gemini 1.5 Pro — Real-time predictive analytics and operational intelligence</p>
              </div>
              <div className="reports-meta">
                <span className="badge badge-green">
                  <span className="status-dot live" style={{ width: 6, height: 6 }} />
                  Auto-updating every 2min
                </span>
              </div>
            </div>

            <div className="reports-list" role="list">
              {insights.map(insight => (
                <div key={insight.id} role="listitem">
                  <AIReportCard insight={insight} />
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
